### ISSUE TITLE
Forcing data from iRODS and thredds

### ISSUE THREAD

**Issue by igarousi** [igarousi/NWC-SI-2017#3]

**Comment by igarousi** [comment]
1- Install CentOs 7 (since iRODS is not available for ubuntu 16 yet). 
     1-1- Use this article to install CentOs on your VM http://www.jeramysingleton.com/install-centos-7-minimal-in-virtualbox/
      Minimal ISO is used!

2- Install iCommands from: https://irods.org/download/
      sudo yum install epel-release
      sudo yum install irods-server irods-database-plugin-postgres

3- NWM data access via iRODS
    3-1- [root@localhost ~]#  iinit
                                                      host name:  nwm.renci.org
                                                      port number:  1247
                                                      username: nwm-reader
                                                      irods zone: nwmZone
                                                      password: nwmreader

4- After seeing Enter your current iRODS password: 
    4-1- [root@localhost ~]#  ils
     Then, you will see /nwmZone/home/nwm-reader:

5- Once the iinit process is completed, the iCommands calls can be made using the saved credentials for the nwm-reader account.   In order to view the NWM data using the nwm-reader account, we need to navigate to the iRODS directory where the data is being stored. The NWM data will be found in: /nwmZone/home/nwm/data
     5-1- [root@localhost ~]#  icd /nwmZone/home/nwm/data
             [root@localhost ~]#  ils
             /nwmZone/home/nwm/data:
                C-  /nwmZone/home/nwm/data/fe_analysis_assim
                C-  /nwmZone/home/nwm/data/forcing_analysis_assim
     5-2- [root@localhost ~]#  iget /nwmZone/home/nwm/data/fe_analysis_assim/nwm.20160919.t05z.fe_analysis_assim.tm00.conus.nc_georeferenced.nc

**Comment by igarousi** [comment]
August 15, 2017
--------------------------------------------------------------------------------------------------------------------------
I was downloading the data from RENCI using iRODS and then uploading them on Mt Moran using globus online.  This process was very time-consuming and inefficient.  So, Dr. Tarboton provide a better way to get the data directly from Mt Moran.  Nels helped us provide a script to download the data on Mt Moran.  Since my account is not defined to submit jobs, Nels is running the script using his own account.  

I have already uploaded Dec and Nov 2016, and also Jan 2017 (1st-11th) on /gscratch/train115/nwm-forcing.  The rest of data (i.e. Feb and Mar 2017 and also Jan (12th-31st) is in progress.

There are several days without any forcing data.  We need to ask Fernando about them.

**Comment by igarousi** [comment]
August 17, 2017
--------------------------------------------------------------------------------------------------------------------------
Downloading forcing data is finished on Mt Moran from thredds server except for those days without data.  We need to ask Fernando and make sure if there are no data, we have to consider some assumptions.

**Comment by igarousi** [comment]
August 18, 2017
------------------------------------------------------------------------
Regarding the missing data, this is Nels's response:
````diff
In terms of missing data, the way the system currently works is it simply ignores it and continues until the next available.  Then ADHydro will read the forcing and apply that forcing until the next available.  It is possible to change the way we handle missing data at creation time, but it may take a little work.
````

**Comment by SiweiHo** [comment]
Since we plan to do one snow season simulation at hourly time step, I think it is acceptable to replace three days missing data with the day before or after. Also, these forcing data are separately saved each hour, I think the easiest way to fill missing data is copying and renaming!
